export const LOGIN = 'users/LOGIN';

export const CREATE_JOB_POSTING = 'CREATE_JOB_POSTING';
export const LOAD_JOBS_SUCCESS = 'LOAD_JOBS_SUCCESS';
export const LOAD_SAVED_JOBS_SUCCESS = 'LOAD_SAVED_JOBS_SUCCESS';
export const LOAD_INTERVIEWS_SUCCESS = 'LOAD_INTERVIEWS_SUCCESS';
